---
- name: Install webmin/usermin/virtualmin
  hosts: all
  tasks:
    - name: Install webmin key
      apt_key: # http://software.virtualmin.com/lib/RPM-GPG-KEY-webmin
        state: "present"
        data: |
              -----BEGIN PGP PUBLIC KEY BLOCK-----
              Version: GnuPG v1.0.7 (GNU/Linux)

              mQGiBDx9wR0RBACR3xGPTkG5Staj7EVeiVJDrYXIPF28MGCrOEGw04tQmQTALz0E
              YEcyfvui7KScrpHmZpy70PwgwxUDPUMik7vvRiUa9RRbJsDYyom06NGk+Z4dURhn
              DeNRhcBrNBfyMvUY7HSJ2JP9jhQDWb8Lo1i231tvlnY0tNudVsP484ax6wCgrBwW
              myad6TLYaETj0+AxGJxYgikD/iERqNF60x+WyfEH/SIOuKGlV/QoxmqOePn2gj9V
              DWiOOAZ9DDWD6DpRNK/UVZRD1MK37HU1ePv7i92DTL9yIbyJwFcZNkEyMU3t+GBj
              zf4YvaQnvtA09EdQNsC1GXxNXqYkVmTE1dHH83UK+chaXRoDQ6O9KD9SFE2vsj1d
              z9VPBACPgmuVcUKXag6ZBY+SBColQzwyZfXtTOCnBh0HP4HOjU4G6CRTcAgLQrdM
              1Uu29Al7TaE2p8HZb37dVoTRntM+Nf5O+2dX5iHA6ncdozKGftuXQMC7z9758nUi
              2E4Svo9hmroM+NKonpZByt6TilhDXrPIcNYHlNsxpTAxq+lnw7QjSmFtaWUgQ2Ft
              ZXJvbiA8amNhbWVyb25Ad2VibWluLmNvbT6IVwQTEQIAFwUCPH3BHQULBwoDBAMV
              AwIDFgIBAheAAAoJENl6OukR9jxRQZEAoIHxngo/LxLBeFF9cpEViVGgChRIAJ90
              zwqcBfw02su5AavnXjv6HxXF8bkBDQQ8fcEqEAQAx88aO9zI912/tbsNjLhDXpq0
              WMw5F6fUUlwYpkaspPwWZ3UgDJaR1+oL3xnJKlD1Eu5x9B3r+rxYyoFpXubWz4R6
              sL1u4kMRb347+fv140dE/RGFNEmqefZDeysz1TQG1Sskyyf7sV2KRUmI8wJTwg3n
              IOtbyOoE3XlxI5FUrW8AAwUD/iEBdIH5DYB/FnOb/EkP3G3kCXGgTdZk7UA9HPKB
              dV7JckgSicpi/mX898LxQrr0jyb6nyi2900OgQUQArrviTnp37j4ciQj214gTHzf
              ssA40O5QR4t915z6wS4Ml+fAc5ZOeL6EQxiP+x+rz6h9+Mc8rawowY+7sBnvVw5O
              YoVXiEYEGBECAAYFAjx9wSoACgkQ2Xo66RH2PFH+ZgCggAyuOLaoE9t9tyJbifEz
              /YzvqYwAnj85Ehe8EmnKuor/k/TPtKl4MzDm
              =oxvD
              -----END PGP PUBLIC KEY BLOCK-----
    - name: Install virtualmin key
      apt_key: # http://software.virtualmin.com/lib/RPM-GPG-KEY-virtualmin
        state: "present"
        data: |
              -----BEGIN PGP PUBLIC KEY BLOCK-----
              Version: GnuPG v1.4.1 (GNU/Linux)

              mQGiBELR2DcRBACD0l3xYWb6c1whtnrKcPVQGW7AGDYy/PEHhUSsY7Qwg5CoYziS
              FSkqXQPhe4P1FqHjvOpZHNfOdC3pSdTgZZYw/DIik3T5NvYbwp+z9GxxIUE9kkt/
              uztb75q/QW7mMy9TJHdK883QC3G47nxGXTnO0p6GaTcHBrF/htR/oLXZ/wCgz4dt
              PKGcShiWOUzZ6mIBSl2PHWkD/iY/+OFa6Va5igra0SXQjNxqG/L6prsUlWtqMAVq
              wjv5UXVCwjBLHl5OUtEz2ky6TgxXOxLsk2p9g9CdZizkhBnLiECXTvnJl5nuwBuz
              YGoijbVx/86amUhHupyQp4QvwopI8U3306SWak3eoNRXNkt/pdJ0WZ+WPsVtZXj/
              1Za3A/9aWS9Rj0YvfzT4/DljQvmHNWutLgKuORYY6HQp8i/ZIlPokkf5Sa4qpbCS
              CU1kiFLRoLbooar1TPhGjusmDn2Re3OxZncHKXPokbNZ1yjiDUd0E0b0Di/ZtVo9
              ODCbJxZd2ONvJwI6ZaM8wKTpRYz+ltryOZ2+orPzivo5ClShLbQqVmlydHVhbG1p
              biwgSW5jLiA8c2VjdXJpdHlAdmlydHVhbG1pbi5jb20+iF4EExECAB4FAkLR2DcC
              GwMGCwkIBwMCAxUCAwMWAgECHgECF4AACgkQ6N0/oKC9vPlIOgCgoxnWKxwADLGt
              5KmVyxISwlvR3sEAn0/iNUd3/hKWurPnoY58zyrTaCrXuQINBELR2EQQCAD7PZNM
              QoVPBZrEjVpIz4nL/QJeJpmOKQXs/mHtIZfCz0tAp/q+rqI+kM/ALXsFpkKQwG0K
              ExWddzL1qlabozb3BR/7ZHAhBQAfIGsC6HY00d/BXA+T2l5RrbkZ7ijDVeN8jRTD
              JkMzNY7+PboqxgSKrQUom3zgO9LZ7sh8o7BP9wIDf71YQq1PvdFaz8FnFp6Kp9NM
              EnW3jQe1VmaHZ32HQ2gk39n/Ihabewy4A7yKqi6uNgukn+7fOrFl4i2VA5+euWe8
              bCzQutcdMkjSIEQkKzLPLN2v55kQdVtnG89eunwMO7+o8VdbWtN1W5KYeRm+xHOG
              o9xZFuhtr1MlJSuTAAMFCADgm2QHNsR4gD0N00cVXp/s38vfG/Cygy7+/RbO8lhL
              mkUVfeG7DWP5x51y7bgQ2hvO169ql0W+GbDj7aG7ZsUY6cXN1Z+ExPTF7T0gMEUy
              tld1dypyzKZqPLMfdFVg4aiE2W9uecj597nYUGrmG7nYnT3/FyC0ouE8KlIGm/iC
              m41GpktYG0H5ed8yhcB+6cUB/2pkneeJIOcKVTp12kB3zcGBtVmD0ITDOmKf4I5W
              TWa1qkyPu1ljFcnVURMQMZoeiJZ03U13TjIWALPUjvfH1k28OAObKj7ljWwRo50P
              qvHbYtShiH5/OiMidFVO2E0p9LdWuJ4bSHoKCFCNvOtuiEkEGBECAAkFAkLR2EQC
              GwwACgkQ6N0/oKC9vPnIEACgjmNJTUFRok6U/AZ/KIOAbKVuY44An0K4VDHVlWp3
              TC+VEV9c7jCjeH3P
              =5DLX
              -----END PGP PUBLIC KEY BLOCK-----
    - name: Install virtualmin
      script: scripts/install.sh -f
      args:
        creates: /etc/webmin/virtual-server/config
      notify:
        - virtualmin first install
    - name: Install additional packages
      package:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'webmin-virtualmin-mailman'
        - 'letsencrypt'
        - 'php7.0-zip'
      notify:
        - restart virtualmin
    - name: Activate apache modules
      apache2_module:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'rewrite'
      notify:
        - restart apache2
    - name: Configure strong ciphers for HTTPS 1/2
      copy:
        content: |
          <IfModule mod_ssl.c>
            SSLHonorCipherOrder on
            SSLProtocol -SSLv3 -TLSv1 -TLSv1.1
            SSLCipherSuite ECDHE:EECDH:DHE:EDH:!MEDIUM:!LOW:!EXPORT:!EXPORT40:!EXPORT56:!AES128:!CAMELLIA:!3DES:!MD5:!aNULL:!eNULL
          </IfModule>
        dest: '/etc/apache2/conf-available/strong-ciphers.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - restart apache2
    - name: Configure strong ciphers for HTTP 2/2
      file:
        src: '/etc/apache2/conf-available/strong-ciphers.conf'
        dest: '/etc/apache2/conf-enabled/strong-ciphers.conf'
        owner: 'root'
        group: 'root'
        state: link
      notify:
        - restart apache2
    - name: Enable password SSH logins for users
      lineinfile:
        state: 'present'
        dest: '/etc/ssh/sshd_config'
        line: '{{ item.line }}'
        regexp: '{{ item.regexp }}'
      with_items:
        - { line: 'PermitRootLogin without-password', regexp: '^\s*PermitRootLogin\s'}
        - { line: 'ChallengeResponseAuthentication yes', regexp: '^\s*ChallengeResponseAuthentication\s'}
        - { line: 'PasswordAuthentication no', regexp: '^\s*PasswordAuthentication\s'}
      notify:
        - restart ssh

      
  handlers:
    - name: virtualmin first install
      lineinfile:
        state: 'present'
        dest: '{{ item.dest }}'
        line: '{{ item.line }}'
        regexp: '{{ item.regexp }}'
      with_items:
        - { dest: '/etc/webmin/config', line: 'theme=authentic-theme', regexp: '^theme='}
        - { dest: '/etc/webmin/miniserv.conf', line: 'preroot=authentic-theme', regexp: '^preroot='}
      notify:
        - restart virtualmin
    - name: restart virtualmin
      service: name=webmin state=restarted
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart ssh
      service: name=ssh state=restarted


- name: Perform upgrades and reboot hosts
  hosts: all
  tasks:
  - name: Update and upgrade all packages
    apt: update_cache=yes autoremove=yes upgrade=yes
  - name: Reboot system if required
    command: shutdown -r now 'Rebooting to complete system upgrade'
             removes=/var/run/reboot-required
