---
- name: Install and configure basic servers
  hosts: all
  tasks:
    - name: Install Apache, PHP7, MariaDB
      package:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - mariadb-client
        - mariadb-server
        - apache2
        - apache2-utils
        - php7.0-gd
        - php7.0-mysql
        - php7.0-imap
        - php7.0-cli
        - php7.0-fpm
        - libapache2-mod-fcgid
        - php-pear
        - php-auth
        - php7.0-mcrypt
        - php7.0-curl
        - php7.0-intl
        - php7.0-pspell
        - php7.0-recode
        - php7.0-sqlite3
        - php7.0-tidy
        - php7.0-xmlrpc
        - php7.0-xsl
        - php-imagick
        - php-gettext
        - php7.0-zip
        - php7.0-mbstring
    - name: Enable Apache modules
      apache2_module:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - actions
        - rewrite
        - alias
      notify:
        - restart apache
    - name: Enable PHP via fpm
      file:
        path: /etc/apache2/conf-enabled/php7.0-fpm.conf
        src: ../conf-available/php7.0-fpm.conf
        state: link
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

- name: Install webmin/usermin/virtualmin
  hosts: all
  tasks:
    - name: Install *min key
      apt_key:
        state: "present"
        data: |
              -----BEGIN PGP PUBLIC KEY BLOCK-----
              Version: GnuPG v1.0.7 (GNU/Linux)

              mQGiBDx9wR0RBACR3xGPTkG5Staj7EVeiVJDrYXIPF28MGCrOEGw04tQmQTALz0E
              YEcyfvui7KScrpHmZpy70PwgwxUDPUMik7vvRiUa9RRbJsDYyom06NGk+Z4dURhn
              DeNRhcBrNBfyMvUY7HSJ2JP9jhQDWb8Lo1i231tvlnY0tNudVsP484ax6wCgrBwW
              myad6TLYaETj0+AxGJxYgikD/iERqNF60x+WyfEH/SIOuKGlV/QoxmqOePn2gj9V
              DWiOOAZ9DDWD6DpRNK/UVZRD1MK37HU1ePv7i92DTL9yIbyJwFcZNkEyMU3t+GBj
              zf4YvaQnvtA09EdQNsC1GXxNXqYkVmTE1dHH83UK+chaXRoDQ6O9KD9SFE2vsj1d
              z9VPBACPgmuVcUKXag6ZBY+SBColQzwyZfXtTOCnBh0HP4HOjU4G6CRTcAgLQrdM
              1Uu29Al7TaE2p8HZb37dVoTRntM+Nf5O+2dX5iHA6ncdozKGftuXQMC7z9758nUi
              2E4Svo9hmroM+NKonpZByt6TilhDXrPIcNYHlNsxpTAxq+lnw7QjSmFtaWUgQ2Ft
              ZXJvbiA8amNhbWVyb25Ad2VibWluLmNvbT6IVwQTEQIAFwUCPH3BHQULBwoDBAMV
              AwIDFgIBAheAAAoJENl6OukR9jxRQZEAoIHxngo/LxLBeFF9cpEViVGgChRIAJ90
              zwqcBfw02su5AavnXjv6HxXF8bkBDQQ8fcEqEAQAx88aO9zI912/tbsNjLhDXpq0
              WMw5F6fUUlwYpkaspPwWZ3UgDJaR1+oL3xnJKlD1Eu5x9B3r+rxYyoFpXubWz4R6
              sL1u4kMRb347+fv140dE/RGFNEmqefZDeysz1TQG1Sskyyf7sV2KRUmI8wJTwg3n
              IOtbyOoE3XlxI5FUrW8AAwUD/iEBdIH5DYB/FnOb/EkP3G3kCXGgTdZk7UA9HPKB
              dV7JckgSicpi/mX898LxQrr0jyb6nyi2900OgQUQArrviTnp37j4ciQj214gTHzf
              ssA40O5QR4t915z6wS4Ml+fAc5ZOeL6EQxiP+x+rz6h9+Mc8rawowY+7sBnvVw5O
              YoVXiEYEGBECAAYFAjx9wSoACgkQ2Xo66RH2PFH+ZgCggAyuOLaoE9t9tyJbifEz
              /YzvqYwAnj85Ehe8EmnKuor/k/TPtKl4MzDm
              =oxvD
              -----END PGP PUBLIC KEY BLOCK-----
      notify: restart metamin

    - name: Add *min repositories
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb http://download.webmin.com/download/repository sarge contrib" }
        - { state: "present", repo: "deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib" }
      notify: restart metamin

    - name: Install webmin, usermin, virtualmin
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "webmin" }
        - { state: "latest", name: "usermin"}
        - { state: "latest", name: "usermin-webmail"}
      notify: restart metamin
  
  handlers:
    - name: restart metamin
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { name: "webmin", state: "restarted"}
        - { name: "usermin", state: "restarted"}
        - { name: "virtualmin", state: "restarted"}


- name: Perform upgrades and reboot hosts
  hosts: all
  tasks:
  - name: Update and upgrade all packages
    apt: update_cache=yes autoremove=yes upgrade=yes
  - name: Reboot system if required
    command: shutdown -r now 'Rebooting to complete system upgrade'
             removes=/var/run/reboot-required
