- name: Install software
  package:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'clamav-milter'
    - 'debconf-utils'

- name: Configure clamav-milter debconf
  debconf:
    name: clamav-milter
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype if "vtype" in item else "string" }}'
  with_items:
    - { question: 'clamav-milter/AddGroups', value: 'postdrop clamav' }
    - { question: 'clamav-milter/LogClean', value: 'Basic', vtype: 'select' }
    - { question: 'clamav-milter/LogInfected', value: 'Basic', vtype: 'select' }
    - { question: 'clamav-milter/OnInfected', value: 'Reject', type: 'select' }
    - { question: 'clamav-milter/RejectMsg', value: 'Message rejected because a virus was detected: %v' }
    - { question: 'clamav-milter/SupportMultipleRecipients', value: 'true' }
    - { question: 'clamav-milter/MilterSocket', value: '/var/spool/postfix/var/run/clamav/clamav-milter.ctl' }

- name: Start and enable clamav-daemon
  service: name=clamav-daemon state=started enabled=true
- name: (Re)start and enable clamav-milter
  service: name=clamav-milter state=restarted enabled=true

# FIXME: This always notifies
- name: Prepare Postfix for milters
  command: postconf -e milter_protocol=2 milter_default_action=accept
  notify: restart postfix

- name: Get smtpd_milters
  command: postconf -h smtpd_milters
  register: smtpd_milters
  changed_when: false
- name: Set smtpd_milters
  command: postconf -e "smtpd_milters = {{ smtpd_milters.stdout }} unix:var/run/clamav/clamav-milter.ctl"
  when: not "var/run/clamav/clamav-milter.ctl" in smtpd_milters.stdout
  notify: restart postfix

- name: Get non_smtpd_milters
  command: postconf -h non_smtpd_milters
  register: non_smtpd_milters
  changed_when: false
- name: Set non_smtpd_milters
  command: postconf -e "non_smtpd_milters = {{ non_smtpd_milters.stdout }} unix:var/run/clamav/clamav-milter.ctl"
  when: not "var/run/clamav/clamav-milter.ctl" in non_smtpd_milters.stdout
  notify: restart postfix
